# -*- coding: utf-8 -*-
"""Demo_LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTrlUOq0QkloQFrdwHdzmNwUl4SyoND9

###**Model**
"""

import pandas as pd
import matplotlib.pyplot as plt
import zipfile
from tqdm import tqdm
from PIL import Image
import pickle
import torch
from torch import nn
from transformers import CLIPProcessor, CLIPModel
import os
from openai import OpenAI
from getpass import getpass

# Hide Warnings
import warnings
warnings.filterwarnings("ignore")

# device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

from google.colab import drive
drive.mount('/content/drive')

# Unzip dataset
!cp /content/drive/MyDrive/dataset.zip /content/
with zipfile.ZipFile("/content/dataset.zip", "r") as z:
    files = z.infolist()

    for file in tqdm(files, desc="Extracting dataset"):     # Progress bar
        z.extract(file.filename, path="/content/dataset")

# Model
num_classes = 300
model = nn.Sequential(
    nn.Linear(2048, 512),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(512, num_classes))

# Load Model
model.load_state_dict(torch.load("/content/drive/MyDrive/best_model.pt", map_location=device))
model = model.to(device)
model.eval()

# Clip Model
clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

clip_model = clip_model.to(device)
clip_model.eval()

# Load Mapping
with open("/content/drive/MyDrive/answer_to_idx.pkl", "rb") as f:
    answer_to_idx = pickle.load(f)

idx_to_answer = {v: k for k, v in answer_to_idx.items()}

# Load Datasets
train_df = pd.read_csv("/content/dataset/dataset/data_train.csv")
val_df = pd.read_csv("/content/dataset/dataset/data_eval.csv")

print(len(val_df))
print(val_df.head())

# Convert datasets to dataframe
train_df["image_path"] = "/content/dataset/dataset/images/" + train_df["image_id"] + ".png"
val_df["image_path"] = "/content/dataset/dataset/images/" + val_df["image_id"] + ".png"

val_df.head()

# Clean train answers
train_df["answers"] = train_df["answer"].apply(lambda x: [a.strip() for a in x.split(",")])

train_exp = train_df.explode("answers")

answer_freq = train_exp["answers"].value_counts()

# Return the most frequent answer from a list
def pick_best_ans(ans_list):
    ans_list = [a.strip() for a in ans_list]
    return max(ans_list, key=lambda x: answer_freq.get(x, 0))

train_df["answer"] = train_df["answers"].apply(pick_best_ans)
train_df = train_df.drop(columns=["answers"])

# Clean validation answers
val_df["answers"] = val_df["answer"].apply(lambda x: [a.strip() for a in x.split(",")])

val_df["answer"] = val_df["answers"].apply(pick_best_ans)

val_df = val_df.drop(columns=["answers"])

# Filter top answers
top_answers = train_df["answer"].value_counts().nlargest(300).index

train_df = train_df[train_df["answer"].isin(top_answers)]
val_df = val_df[val_df["answer"].isin(top_answers)]

# Create a mapping from each answer to a unique index
answer_to_idx = {ans: i for i, ans in enumerate(top_answers)}

train_df["label"] = train_df["answer"].map(answer_to_idx)
val_df["label"] = val_df["answer"].map(answer_to_idx)

# Fusion Function
def fuse_features(q_feat, img_feat):

    mul = q_feat * img_feat
    diff = torch.abs(q_feat - img_feat)

    fused = torch.cat([q_feat, img_feat, mul, diff], dim=1)

    return fused

# Predict Function
def predict(image_path, question):

    # TEXT
    inputs_q = processor(
        text=[question],
        return_tensors="pt",
        padding=True,
        truncation=True
    )
    inputs_q = {k: v.to(device) for k, v in inputs_q.items()}

    with torch.no_grad():
        q_feat_output = clip_model.get_text_features(**inputs_q)
        # Extract the tensor if the output is BaseModelOutputWithPooling
        q_feat = q_feat_output.pooler_output if hasattr(q_feat_output, 'pooler_output') else q_feat_output

    # IMAGE
    image = Image.open(image_path).convert("RGB")

    inputs_img = processor(images=[image], return_tensors="pt")
    inputs_img = {k: v.to(device) for k, v in inputs_img.items()}

    with torch.no_grad():
        img_feat_output = clip_model.get_image_features(**inputs_img)
        # Extract the tensor if the output is BaseModelOutputWithPooling
        img_feat = img_feat_output.pooler_output if hasattr(img_feat_output, 'pooler_output') else img_feat_output

    # FUSE
    x = fuse_features(q_feat, img_feat)

    # PREDICT
    with torch.no_grad():
        out = model(x)
        probs = torch.softmax(out, dim=1)

        pred = torch.argmax(probs, dim=1).item()
        confidence = probs[0][pred].item()

    answer = idx_to_answer[pred]

    # top3
    topk = torch.topk(probs, 3)
    top_answers = [idx_to_answer[i.item()] for i in topk.indices[0]]
    top_scores = [round(v.item(), 3) for v in topk.values[0]]

    return answer, confidence, top_answers, top_scores

def show_demo(image_path, question):

    img = Image.open(image_path)

    answer, conf, top_ans, top_scores = predict(image_path, question)

    plt.imshow(img)
    plt.axis("off")

    plt.title(
        f"Q: {question}\n"
        f"A: {answer} ({conf:.2f})\n"
        f"Top3: {list(zip(top_ans, top_scores))}"
    )

    plt.show()

# Load answer to index mapping and create index to answer mapping
with open("/content/drive/MyDrive/answer_to_idx.pkl", "rb") as f:
    answer_to_idx = pickle.load(f)

idx_to_answer = {v: k for k, v in answer_to_idx.items()}

"""###**LLM**"""

# API


os.environ["OPENAI_API_KEY"] = getpass("Enter your API key:")
client = OpenAI()

# LLM Function
def generate_llm_answer(question, answer, confidence):

    prompt = f"""
You are an AI assistant.

Answer the question naturally using the given short answer.

Question: {question}
Short Answer: {answer}

Write a short, natural sentence.
"""

    response = client.chat.completions.create(
        model="gpt-5",
        messages=[{"role": "user", "content": prompt}])

    return response.choices[0].message.content

def get_true_answer(image_path, question):

    row = val_df[
        (val_df["image_path"] == image_path) &
        (val_df["question"] == question)
    ]

    if len(row) > 0:
        return row.iloc[0]["answer"]
    else:
        return "Not found"

# Demo
import matplotlib.pyplot as plt
from PIL import Image

def demo(image_path, question):

    # Model Prediction
    answer, conf, top_ans, top_scores = predict(image_path, question)

    # LLM
    llm_answer = generate_llm_answer(question, answer, conf)

    true_answer = get_true_answer(image_path, question)

    # Show Image
    img = Image.open(image_path)
    plt.imshow(img)
    plt.axis("off")

    # Title
    plt.title(
        f"Q: {question}\n"
        f"Model: {answer}\n"
        f"Top3: {list(zip(top_ans, top_scores))}")
    plt.show()

    # Print LLM

    if true_answer != "Not found":
        print("\n🤖 True Answer:")
        print(true_answer)

    print("\n🧠 LLM Answer:")
    print(llm_answer)

img_path = "/content/dataset/dataset/images/image694.png"
question = "what is the colour of the towel"

demo(img_path, question)

img_path = "/content/dataset/dataset/images/image1320.png"
question = "what are found on the rack"

demo(img_path, question)

